# Generated by Django 5.0.1 on 2024-07-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_serviceuser_order_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceuser",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
